Commented out "pytorch3d" and "class BinsChamferLoss".
while training the error shows 
Traceback (most recent call last):
  File "/content/AdaBins_modified/train.py", line 21, in <module>
    from loss import SILogLoss, BinsChamferLoss
  File "/content/AdaBins_modified/loss.py", line 3, in <module>
    from pytorch3d.loss import chamfer_distance
ModuleNotFoundError: No module named 'pytorch3d'

There is some problem related to pytorch3d library occuring inside loss.py .
As a result the BinsChamferLoss class will not work properly. Therefore it is omited and not used for training with sample dataset(created by me) for the time being.